services:
  - type: web
    name: military-ai-screening
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000




